#!/bin/bash

# Check to make sure this is running on Linux
# Mac does not seem to support this 
# TODO: look into vagrant usage for this

if [ $(uname) != "Linux" ]
then

    echo "This script only runs on Linux."
    exit 1
fi

# Run from the feature_selection repository

FLOWMETER="cicflowmeter-4.zip"
FLOWMETER_UNZIP="CICFlowMeter-4.0"
ISCX_ENDPOINT="https://iscxdownloads.cs.unb.ca/iscxdownloads/ISCX-Bot-2014/"

if [ -d $FLOWMETER_UNZIP ]
then

    echo "$FLOWMETER_UNZIP already exists in expected spot..."
else

    # Get the tool (should download cic-flowmeter-4.zip into cwd)
    wget http://www.netflowmeter.ca/$FLOWMETER

    # Unzip the package
    unzip -o $FLOWMETER
fi

# Get the datasets

TRAINING_DATASET="ISCX_Botnet-Training.pcap"
TESTING_DATASET="ISCX_Botnet-Testing.pcap"

# Get training dataset

if [ -f $TRAINING_DATASET ]
then

    echo "Training data set already exists in expected spot. Continuing..."
else

    echo "Getting training data set pcap file..."
    wget $ISCX_ENDPOINT/$TRAINING_DATASET
fi

# Get test dataset

if [ -f $TESTING_DATASET ]
then

    echo "Testing dataset already exists in expected spot. Continuing..."
else

    echo "Getting testing data set pcap file..."
    wget $ISCX_ENDPOINT/$TESTING_DATASET
fi

# Create flow csv files

TRAINING_FLOWS="ISCX_Botnet-Training.pcap_Flow.csv"
TESTING_FLOWS="ISCX_Botnet-Testing.pcap_Flow.csv"

# Create training dataset flow file

if [ -f $TRAINING_FLOWS ]
then

    echo "Training dataset flow csv file already exists. Continuing..."
else
    cd ./$FLOWMETER_UNZIP/bin/
    ./cfm ../../$TRAINING_DATASET ../../
    cd ../../
fi

# Create testing dataset flow file

if [ -f $TESTING_FLOWS ]
then

    echo "Testing dataset flow csv file already exists. Continuing..."
else
    cd ./$FLOWMETER_UNZIP/bin/
    ./cfm ../../$TESTING_DATASET ../../
    cd ../../
fi

# Label flows

LABELED_TRAINING_FLOWS="ISCX_Botnet-Training.pcap_Flow_labeled.csv"
LABELED_TESTING_FLOWS="ISCX_Botnet-Testing.pcap_Flow_labeled.csv"

if [ -f $LABELED_TRAINING_FLOWS ] && [ -f $LABELED_TESTING_FLOWS ]
then

    echo "Labeled training and testing flows csv files already exist. Continuiung..."
else

    python add_labels.py $TRAINING_FLOWS $TESTING_FLOWS $LABELED_TRAINING_FLOWS $LABELED_TESTING_FLOWS
fi

echo "Finished."
